/**
 * Blood Compatibility Logic Engine
 * Red Cell Donor to Recipient Compatibility Rules:
 * 
 * - O- (Universal Red Cell Donor): Can give to O-, O+, A-, A+, B-, B+, AB-, AB+
 * - O+: Can give to O+, A+, B+, AB+
 * - A-: Can give to A-, A+, AB-, AB+
 * - A+: Can give to A+, AB+
 * - B-: Can give to B-, B+, AB-, AB+
 * - B+: Can give to B+, AB+
 * - AB-: Can give to AB-, AB+
 * - AB+: Can give to AB+ only (Universal Recipient)
 */

export const BLOOD_COMPATIBILITY_MAP = {
  'O-': ['O-', 'O+', 'A-', 'A+', 'B-', 'B+', 'AB-', 'AB+'],
  'O+': ['O+', 'A+', 'B+', 'AB+'],
  'A-': ['A-', 'A+', 'AB-', 'AB+'],
  'A+': ['A+', 'AB+'],
  'B-': ['B-', 'B+', 'AB-', 'AB+'],
  'B+': ['B+', 'AB+'],
  'AB-': ['AB-', 'AB+'],
  'AB+': ['AB+']
};

/**
 * Recipient to Compatible Donors Map (Who can donate to this recipient)
 */
export const RECIPIENT_COMPATIBILITY_MAP = {
  'O-': ['O-'],
  'O+': ['O-', 'O+'],
  'A-': ['O-', 'A-'],
  'A+': ['O-', 'O+', 'A-', 'A+'],
  'B-': ['O-', 'B-'],
  'B+': ['O-', 'O+', 'B-', 'B+'],
  'AB-': ['O-', 'A-', 'B-', 'AB-'],
  'AB+': ['O-', 'O+', 'A-', 'A+', 'B-', 'B+', 'AB-', 'AB+']
};

/**
 * Check if a donor blood group is compatible with a recipient blood group
 */
export const isCompatible = (donorBloodGroup, recipientBloodGroup) => {
  if (!donorBloodGroup || !recipientBloodGroup) return false;
  const allowedRecipients = BLOOD_COMPATIBILITY_MAP[donorBloodGroup] || [];
  return allowedRecipients.includes(recipientBloodGroup);
};

/**
 * Get all blood groups compatible for donation to a specific recipient blood group
 */
export const getCompatibleDonorsForRecipient = (recipientBloodGroup) => {
  return RECIPIENT_COMPATIBILITY_MAP[recipientBloodGroup] || [recipientBloodGroup];
};

/**
 * Get all recipient blood groups a donor blood group can donate to
 */
export const getCompatibleRecipientsForDonor = (donorBloodGroup) => {
  return BLOOD_COMPATIBILITY_MAP[donorBloodGroup] || [donorBloodGroup];
};

export const MEDICAL_DISCLAIMER = "Disclaimer: Compatibility matches generated by LifeLink are based on general ABO/Rh blood grouping standards. Actual medical compatibility, cross-matching, and antibody screening MUST always be performed and verified by qualified healthcare professionals prior to transfusion.";
